import { BlogCard } from '@shared/components/blog-card/blog-card.interfaces';
import { ANGULAR_DATA } from '@shared/data';

export const angularBlogCardList: BlogCard[] = [
  {
    image: ANGULAR_DATA.MATERIAL_TABLE.META.IMAGE,
    imageAlt: ANGULAR_DATA.MATERIAL_TABLE.TITLE,
    date: ANGULAR_DATA.MATERIAL_TABLE.DATE,
    title: ANGULAR_DATA.MATERIAL_TABLE.TITLE,
    url: ANGULAR_DATA.MATERIAL_TABLE.PATH,
  },
  {
    image: ANGULAR_DATA.ADD_CUSTOM_ENVIRONMENTS.META.IMAGE,
    imageAlt: ANGULAR_DATA.ADD_CUSTOM_ENVIRONMENTS.TITLE,
    date: ANGULAR_DATA.ADD_CUSTOM_ENVIRONMENTS.DATE,
    title: ANGULAR_DATA.ADD_CUSTOM_ENVIRONMENTS.TITLE,
    url: ANGULAR_DATA.ADD_CUSTOM_ENVIRONMENTS.PATH,
  },
  {
    image: ANGULAR_DATA.LAZY_LOAD_IMAGES.META.IMAGE,
    imageAlt: ANGULAR_DATA.LAZY_LOAD_IMAGES.TITLE,
    date: ANGULAR_DATA.LAZY_LOAD_IMAGES.DATE,
    title: ANGULAR_DATA.LAZY_LOAD_IMAGES.TITLE,
    url: ANGULAR_DATA.LAZY_LOAD_IMAGES.PATH,
  },
  {
    image: ANGULAR_DATA.BUILD_MOBILE_APPS.META.IMAGE,
    imageAlt: ANGULAR_DATA.BUILD_MOBILE_APPS.TITLE,
    date: ANGULAR_DATA.BUILD_MOBILE_APPS.DATE,
    title: ANGULAR_DATA.BUILD_MOBILE_APPS.TITLE,
    url: ANGULAR_DATA.BUILD_MOBILE_APPS.PATH,
  },
  {
    image: ANGULAR_DATA.DIFFERENTIAL_LOADING.META.IMAGE,
    imageAlt: ANGULAR_DATA.DIFFERENTIAL_LOADING.TITLE,
    date: ANGULAR_DATA.DIFFERENTIAL_LOADING.DATE,
    title: ANGULAR_DATA.DIFFERENTIAL_LOADING.TITLE,
    url: ANGULAR_DATA.DIFFERENTIAL_LOADING.PATH,
  },
];
